/**
 * Shell completion scripts for storyof CLI.
 *
 * Dynamic completions (models, sessions) are generated by calling
 * `storyof --completion-data <type>` which is fast and reads real auth state.
 */

import { APP_CMD } from "./constants.js";

const CMD = APP_CMD;
const FUNC = CMD.replace(/-/g, "_");

// ═══════════════════════════════════════════════════════════════════════
// Bash
// ═══════════════════════════════════════════════════════════════════════

export const BASH_COMPLETION = `
# ${CMD} bash completion
_${FUNC}_completions() {
    local cur prev
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    local commands="auth resume stop completion"
    local flags="--help --version --depth --path --model"
    local auth_commands="set login logout list --help"
    local providers="anthropic openai google groq xai openrouter mistral cerebras github-copilot"
    local oauth_providers="anthropic github-copilot google antigravity openai-codex"
    local depth_levels="shallow medium deep"

    # Flag value completions — works at any position
    case "\${prev}" in
        --depth)
            COMPREPLY=( $(compgen -W "\${depth_levels}" -- "\${cur}") )
            return 0
            ;;
        --model)
            local models
            models="$(${CMD} --completion-data models 2>/dev/null)"
            if [ -n "\${models}" ]; then
                COMPREPLY=( $(compgen -W "\${models}" -- "\${cur}") )
            fi
            return 0
            ;;
        --path)
            COMPREPLY=( $(compgen -d -- "\${cur}") )
            return 0
            ;;
    esac

    # Auth subcommands
    if [ "\${COMP_WORDS[1]}" = "auth" ]; then
        if [ \${COMP_CWORD} -eq 2 ]; then
            COMPREPLY=( $(compgen -W "\${auth_commands}" -- "\${cur}") )
            return 0
        fi
        case "\${COMP_WORDS[2]}" in
            set|logout) [ \${COMP_CWORD} -eq 3 ] && COMPREPLY=( $(compgen -W "\${providers}" -- "\${cur}") ) ;;
            login)      [ \${COMP_CWORD} -eq 3 ] && COMPREPLY=( $(compgen -W "\${oauth_providers}" -- "\${cur}") ) ;;
        esac
        return 0
    fi

    # Completion subcommand
    if [ "\${COMP_WORDS[1]}" = "completion" ]; then
        [ \${COMP_CWORD} -eq 2 ] && COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
        return 0
    fi

    # Resume — suggest sessions
    if [ "\${COMP_WORDS[1]}" = "resume" ]; then
        local sessions
        sessions="$(${CMD} --completion-data sessions 2>/dev/null)"
        [ -n "\${sessions}" ] && COMPREPLY=( $(compgen -W "\${sessions}" -- "\${cur}") )
        return 0
    fi

    # At any position: if current word starts with -, complete flags
    if [[ "\${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "\${flags}" -- "\${cur}") )
        return 0
    fi

    # First non-flag word: commands + flags
    # Check if a command was already given
    local has_cmd=false
    for ((i=1; i<COMP_CWORD; i++)); do
        case "\${COMP_WORDS[i]}" in
            auth|resume|stop|completion) has_cmd=true; break ;;
            --*) ;; # skip flags and their values
            *) ;; 
        esac
    done

    if ! \${has_cmd}; then
        COMPREPLY=( $(compgen -W "\${commands} \${flags}" -- "\${cur}") )
    fi
}

complete -o default -F _${FUNC}_completions ${CMD}
`;

// ═══════════════════════════════════════════════════════════════════════
// Zsh
// ═══════════════════════════════════════════════════════════════════════

export const ZSH_COMPLETION = `
#compdef ${CMD}

_${FUNC}() {
    local -a commands auth_commands providers oauth_providers depth_levels

    commands=(
        'auth:Manage API keys and OAuth tokens'
        'resume:Resume a previous session'
        'stop:Stop the running agent'
        'completion:Generate shell completion script'
    )

    auth_commands=(
        'set:Store an API key'
        'login:OAuth login (opens browser)'
        'logout:Remove stored credentials'
        'list:Show stored credentials'
    )

    providers=(
        'anthropic:Anthropic Claude API'
        'openai:OpenAI API'
        'google:Google AI Studio (Gemini)'
        'groq:Groq API'
        'xai:xAI (Grok)'
        'openrouter:OpenRouter'
        'mistral:Mistral AI'
        'cerebras:Cerebras Cloud'
        'github-copilot:GitHub Copilot'
    )

    oauth_providers=(
        'anthropic:Claude Pro/Max or Team'
        'github-copilot:GitHub Copilot subscription'
        'google:Google Gemini CLI'
        'antigravity:Google Cloud Antigravity'
        'openai-codex:ChatGPT Plus/Pro or Team'
    )

    depth_levels=(
        'shallow:Quick overview'
        'medium:Balanced exploration'
        'deep:Comprehensive analysis'
    )

    # Auth subcommands
    if [[ "\${words[2]}" == "auth" ]]; then
        if (( CURRENT == 3 )); then
            _describe 'auth command' auth_commands; return 0
        fi
        case "\${words[3]}" in
            set|logout) (( CURRENT == 4 )) && _describe 'provider' providers; return 0 ;;
            login)      (( CURRENT == 4 )) && _describe 'oauth provider' oauth_providers; return 0 ;;
        esac
        return 0
    fi

    # Completion subcommand
    if [[ "\${words[2]}" == "completion" ]]; then
        if (( CURRENT == 3 )); then
            local -a shells=('bash:Bash completion' 'zsh:Zsh completion' 'fish:Fish completion')
            _describe 'shell' shells
        fi
        return 0
    fi

    # Resume — suggest sessions
    if [[ "\${words[2]}" == "resume" ]]; then
        local -a sessions
        local raw
        raw="\$(${CMD} --completion-data sessions-zsh 2>/dev/null)"
        if [[ -n "\${raw}" ]]; then
            sessions=("\${(@f)raw}")
            _describe 'session' sessions
        fi
        return 0
    fi

    # Flag value completions — works at any position
    case "\${words[CURRENT-1]}" in
        --depth)
            _describe 'depth level' depth_levels; return 0
            ;;
        --path)
            _files -/; return 0
            ;;
        --model)
            local -a models
            local raw
            raw="\$(${CMD} --completion-data models-zsh 2>/dev/null)"
            if [[ -n "\${raw}" ]]; then
                models=("\${(@f)raw}")
                _describe 'model' models
            fi
            return 0
            ;;
    esac

    # Top-level: commands + flags
    _arguments -s \\
        '(-v --version)'{-v,--version}'[Show version]' \\
        '(-h --help)'{-h,--help}'[Show help]' \\
        '--depth[Exploration depth]:depth level:(shallow medium deep)' \\
        '*--path[Scope to directory]:directory:_files -/' \\
        '--model[AI model]:model:->models' \\
        '*:: :->subcmd'

    case "\${state}" in
        subcmd)
            _describe 'command' commands
            ;;
        models)
            local -a models
            local raw
            raw="\$(${CMD} --completion-data models-zsh 2>/dev/null)"
            if [[ -n "\${raw}" ]]; then
                models=("\${(@f)raw}")
                _describe 'model' models
            fi
            ;;
    esac
}

_${FUNC} "\$@"
`;

// ═══════════════════════════════════════════════════════════════════════
// Fish
// ═══════════════════════════════════════════════════════════════════════

export const FISH_COMPLETION = `
# ${CMD} fish completion

# Disable file completions by default
complete -c ${CMD} -f

# Helper: check if no subcommand given yet
function __${FUNC}_no_subcommand
    set -l tokens (commandline -opc)
    for t in $tokens[2..]
        switch $t
            case auth resume stop completion
                return 1
        end
    end
    return 0
end

# Helper: check previous token
function __${FUNC}_prev_is
    set -l tokens (commandline -opc)
    test "$tokens[-1]" = "$argv[1]"
end

# Top-level commands
complete -c ${CMD} -n __${FUNC}_no_subcommand -a auth -d 'Manage API keys and OAuth tokens'
complete -c ${CMD} -n __${FUNC}_no_subcommand -a resume -d 'Resume a previous session'
complete -c ${CMD} -n __${FUNC}_no_subcommand -a stop -d 'Stop the running agent'
complete -c ${CMD} -n __${FUNC}_no_subcommand -a completion -d 'Generate shell completion script'

# Flags (available everywhere, not just first position)
complete -c ${CMD} -l help -d 'Show help'
complete -c ${CMD} -s v -l version -d 'Show version'
complete -c ${CMD} -l depth -d 'Set exploration depth' -x -a 'shallow medium deep'
complete -c ${CMD} -l path -d 'Scope to directory' -r -F
complete -c ${CMD} -n '__${FUNC}_prev_is --model' -a '(${CMD} --completion-data models 2>/dev/null)' -d 'AI model'
complete -c ${CMD} -l model -d 'Specify AI model' -x

# Completion shells
complete -c ${CMD} -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'

# Auth subcommands
complete -c ${CMD} -n '__fish_seen_subcommand_from auth' -a set -d 'Store an API key'
complete -c ${CMD} -n '__fish_seen_subcommand_from auth' -a login -d 'OAuth login'
complete -c ${CMD} -n '__fish_seen_subcommand_from auth' -a logout -d 'Remove credentials'
complete -c ${CMD} -n '__fish_seen_subcommand_from auth' -a list -d 'Show credentials'

# Auth providers
complete -c ${CMD} -n '__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from set logout' -a 'anthropic openai google groq xai openrouter mistral cerebras github-copilot'
complete -c ${CMD} -n '__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login' -a 'anthropic github-copilot google antigravity openai-codex'

# Resume — dynamic sessions
complete -c ${CMD} -n '__fish_seen_subcommand_from resume' -a '(${CMD} --completion-data sessions 2>/dev/null)'
`;
